"""Unified CLI Test Runner for Pi Agent & CI.

Provides easy commands to run:
- Live Oracle EBS integration tests (real data)
- Deterministic pure rules tests (offline)
- Synthetic invoice corpus regression
- Full test suite with automatic Markdown report generation in `tests/reports/`

Usage:
    python tests/run_tests.py --mode live-oracle
    python tests/run_tests.py --mode offline
    python tests/run_tests.py --all --report
"""

import sys
import os
import time
import argparse
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List

# Ensure UTF-8 output encoding on Windows
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

# Ensure project root is in sys.path
_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

REPORTS_DIR = _ROOT / "tests" / "reports"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)


def run_command(cmd: List[str]) -> tuple[int, str]:
    """Execute a command and return (exit_code, combined_stdout_stderr)."""
    print(f"\n[RUNNING] {' '.join(cmd)}\n")
    proc = subprocess.Popen(
        cmd,
        cwd=str(_ROOT),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="replace"
    )
    output_lines = []
    while True:
        line = proc.stdout.readline()
        if not line and proc.poll() is not None:
            break
        if line:
            try:
                sys.stdout.write(line)
                sys.stdout.flush()
            except Exception:
                pass
            output_lines.append(line)
    
    proc.wait()
    return proc.returncode, "".join(output_lines)


def generate_report(mode: str, exit_code: int, duration: float, output: str):
    """Write standardized execution report to tests/reports/test_run_latest.md."""
    status_str = "PASSED" if exit_code == 0 else "FAILED"
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    report_file = REPORTS_DIR / "test_run_latest.md"
    
    report_content = [
        f"# Pi Agent Test Execution Report",
        f"",
        f"- **Timestamp:** `{timestamp}`",
        f"- **Execution Mode:** `{mode}`",
        f"- **Overall Status:** **{status_str}** (Exit Code: {exit_code})",
        f"- **Duration:** `{duration:.2f}s`",
        f"",
        f"---",
        f"",
        f"## Execution Output Summary",
        f"",
        f"```text",
        output.strip()[-3500:] if len(output) > 3500 else output.strip(),
        f"```",
        f"",
        f"---",
        f"",
        f"> 📌 Auto-generated by `tests/run_tests.py` on behalf of Pi Agent."
    ]
    
    with open(report_file, "w", encoding="utf-8") as f:
        f.write("\n".join(report_content))
    
    print(f"\n[REPORT] Saved latest report to: {report_file}")


def main():
    parser = argparse.ArgumentParser(description="Pi Agent Unified Test Runner")
    parser.add_argument(
        "--mode", "-m",
        choices=["live-oracle", "offline", "corpus", "suite", "all"],
        default="all",
        help="Test execution mode"
    )
    parser.add_argument(
        "--all", "-a",
        action="store_true",
        help="Run all tests"
    )
    parser.add_argument(
        "--report", "-r",
        action="store_true",
        default=True,
        help="Generate Markdown report in tests/reports/ (default: True)"
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Verbose pytest output"
    )

    args = parser.parse_args()
    mode = "all" if args.all else args.mode

    # Determine python executable in .venv if available
    python_bin = sys.executable
    venv_py = _ROOT / ".venv" / "Scripts" / "python.exe"
    if venv_py.exists():
        python_bin = str(venv_py)

    start_time = time.time()
    exit_code = 0
    all_outputs = []

    print("=" * 70)
    print(f"  AIVA PO-INV MATCHING TEST RUNNER (Mode: {mode})")
    print(f"  Python: {python_bin}")
    print("=" * 70)

    if mode in ["live-oracle", "all"]:
        print("\n>>> [1/3] Running Live Oracle EBS Integration Tests...")
        code, out = run_command([
            python_bin, "-m", "pytest",
            "tests/live/test_live_oracle.py",
            "-m", "oracle",
            "-o", "addopts=",
            "-v", "-s"
        ])
        all_outputs.append(out)
        if code != 0:
            exit_code = code

    if mode in ["offline", "all"]:
        print("\n>>> [2/3] Running Offline Deterministic Test Suite...")
        # Runs test_suite.py directly
        code, out = run_command([
            python_bin, "tests/test_suite.py"
        ])
        all_outputs.append(out)
        if code != 0:
            exit_code = code

    if mode in ["corpus", "all"]:
        print("\n>>> [3/3] Running Synthetic Invoice Corpus Pytest...")
        code, out = run_command([
            python_bin, "-m", "pytest",
            "tests/test_invoice_corpus.py",
            "-q"
        ])
        all_outputs.append(out)
        # Note: if corpus dataset not generated, it skips gracefully without failure
        if code not in [0, 5]:  # code 5 is pytest NO_TESTS_COLLECTED / SKIPPED
            exit_code = code

    total_duration = time.time() - start_time
    combined_output = "\n".join(all_outputs)

    if args.report:
        generate_report(mode, exit_code, total_duration, combined_output)

    print("\n" + "=" * 70)
    print(f"  FINAL RESULT: {'SUCCESS (ALL PASSED)' if exit_code == 0 else 'FAILURE DETECTED'}")
    print(f"  Total Duration: {total_duration:.2f}s")
    print("=" * 70)

    sys.exit(exit_code)


if __name__ == "__main__":
    main()
